const PLAYER_READY = "PLAYER_READY";
const LEGAL_GAME_MOVES_FOR_HAND = "LEGAL_GAME_MOVES_FOR_HAND";
const NO_LEGAL_GAME_MOVES_FOR_HAND = "NO_LEGAL_GAME_MOVES_FOR_HAND";
const PLAYER_REQUEST_DOUBLE = "PLAYER_REQUEST_DOUBLE";
const PLAYER_REQUEST_HIT = "PLAYER_REQUEST_HIT";
const PLAYER_RECEIVED_HIT = "PLAYER_RECEIVED_HIT";
const PLAYER_REQUEST_SPLIT = "PLAYER_REQUEST_SPLIT";
const PLAYER_REQUEST_STAND = "PLAYER_REQUEST_STAND";
const PLAYER_HAND_SPLIT = "PLAYER_HAND_SPLIT";
const HAND_SPLIT = "HAND_SPLIT";

const emittableEvents = {
  PLAYER: {
    PLAYER_READY,
    PLAYER_REQUEST_DOUBLE,
    PLAYER_REQUEST_HIT,
    PLAYER_RECEIVED_HIT,
    PLAYER_REQUEST_SPLIT,
    PLAYER_REQUEST_STAND
  },
  HAND: {
    LEGAL_GAME_MOVES_FOR_HAND,
    NO_LEGAL_GAME_MOVES_FOR_HAND,
    HAND_SPLIT
  },

  PLAYER_READY,
  LEGAL_GAME_MOVES_FOR_HAND,
  NO_LEGAL_GAME_MOVES_FOR_HAND,
  PLAYER_REQUEST_DOUBLE,
  PLAYER_REQUEST_HIT,
  PLAYER_RECEIVED_HIT,
  PLAYER_REQUEST_SPLIT,
  PLAYER_REQUEST_STAND,
  PLAYER_HAND_SPLIT
};
export { emittableEvents };
